name: Authentication Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Create .env file for backend
        run: |
          cat > backend/.env << EOF
          DB_HOST=db
          DB_USER=postgres
          DB_PASSWORD=postgres
          DB_NAME=mydatabase
          DB_PORT=5432
          JWT_SECRET=env.JWT_SECRET
          PORT=5000
          EOF

      - name: Build and start Docker containers
        run: |
          docker compose up -d --build
          echo "Waiting for services to be ready..."
          sleep 10

      - name: Wait for backend to be ready
        run: |
          echo "Checking backend health..."
          for i in {1..30}; do
            if curl -f http://localhost:5000/api/categories > /dev/null 2>&1; then
              echo "Backend is ready!"
              break
            fi
            echo "Waiting for backend... ($i/30)"
            sleep 2
          done

      - name: Run authentication tests
        run: npm test

      - name: Show Docker logs on failure
        if: failure()
        run: |
          echo "=== Backend logs ==="
          docker compose logs backend
          echo "=== Database logs ==="
          docker compose logs db

      - name: Stop Docker containers
        if: always()
        run: docker compose down -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            test-results/
